### ISSUE TITLE
Large input file breaks build

### ISSUE THREAD

**Issue by marcinkrasowski** [Aratramba/pug-doc-html#8]
An issue appeared in a project with a lot of jade documentation: when input json is too large (over 40 kB) this line

`var json = JSON.parse(data.toString());`

causes an error because `data` is only a 40kB chunk of the whole file (and, therefore, is in an incorrect json format). A simple solution would be to aggregate this data:

``` javascript
// read input json
var input = fs.createReadStream(__dirname +'/'+ options.input);

var jsonData = '';
input.on('data', function(data){
    jsonData += data.toString();
});
```

and then parse it only after the stream ends:

``` javascript
input.on('end', function(data){
    var json = JSON.parse(jsonData);
    // rest of the code
}
```

**Comment by Aratramba** [comment]
makes sense, I'll fix it.

**Comment by Aratramba** [comment]
new version is on npm

**Comment by marcinkrasowski** [comment]
Great, thanks!
