### ISSUE TITLE
How this package can works with jade-doc??

### ISSUE THREAD

**Issue by MACruzDeveloper** [Aratramba/pug-doc-html#9]
Hi,

I'm trying to get an html doc based on json maked by jade-doc package, but it doesn't work if json file isn't created before. I have tested it with callbacks, another packages like run-sequence or gulp-sync but I don´t get nothing. My code now:

gulp.task('jadeDocJson', function () {  
    jadeDoc({
        input: 'doc.jade',
        output: 'node_modules/jade-doc-html/doc.json'
    });
});
gulp.task('jadeDocHtml', ['jadeDocJson'], function(){
    var jdh = new JadeDocHTML({
        output: 'doc.html',
        input: 'doc.json'
    }); 
});
gulp.task('jadeDoc', ['jadeDocJson', 'jadeDocHtml']);

Any idea??
Thanks!

**Comment by Aratramba** [comment]
so the complete callback doesn't work for you? Maybe something like this (untested)?

``` js
pugDoc({
  input: 'doc.jade',
  output: 'node_modules/jade-doc-html/doc.json',
  complete: function() {
    new JadeDocHTML({
      output: 'doc.html',
      input: 'node_modules/jade-doc-html/doc.json'
    }); 
  }
});
```

or use the `complete: function(){}` for pugDoc and `stream.on('complete', function(){})` for pugDocHTML to call the callbacks of the gulp tasks. Haven't tested this code, but it should be something like this I guess.

``` js
gulp.task('pug-doc', function(cb) {
  pugDoc({
    input: 'doc.jade',
    output: 'node_modules/pug-doc-html/doc.json',
    complete: cb
  });
}

gulp.task('pug-doc-html', function(cb) {
  var stream = new PugDocHTML({
    output: 'doc.html',
    input: 'node_modules/pug-doc-html/doc.json'
  });

  stream.on('complete', function(){
    cb();
  });
}

gulp.task('jadeDoc', ['pug-doc', 'pug-doc-html']);
```

**Comment by MACruzDeveloper** [comment]
I've tested your code and I've got with this final code:

```
gulp.task('jadedocu', function () {  
    pugDoc({
        input: 'doc.jade',
        output: 'node_modules/pug-doc-html/doc.json',
        complete: function() {
            new pugDocHTML({
                output: 'doc.html',
                input: 'doc.json'
            }); 
        }
    });
});
```

I tested the same code with packages jade-doc and jade-doc-html and it didn't work, but with pug-doc and pug-doc-html worked perfectly!

Thanks!

**Comment by Aratramba** [comment]
awesome.
